name: climatehack
channels:
  - conda-forge
dependencies:
  - xarray
  - zarr
  - numpy
  - matplotlib
  - gcsfs
  - fsspec
  - dask
  - cartopy  
  - pip:
    - einops==0.4.0
    - opencv-python==4.5.5.62
    - pytorch-msssim==0.2.1
    - ray==1.10.0
    - tqdm==4.62.3
