channels:
  - conda-forge
dependencies:
  - xarray
  - zarr
  - numpy
  - matplotlib
  - gcsfs
  - fsspec
  - dask
  - cartopy  
  - pip:
    - einops
    - opencv-python
    - pytorch-msssim
    - ray
    - tqdm
